/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FooterMusic: typeof import('./src/components/item/FooterMusic.vue')['default']
    ItemMusicList: typeof import('./src/components/item/ItemMusicList.vue')['default']
    ItemMusicTop: typeof import('./src/components/item/ItemMusicTop.vue')['default']
    MedNav: typeof import('./src/components/home/MedNav.vue')['default']
    MusicDetail: typeof import('./src/components/item/MusicDetail.vue')['default']
    MusicList: typeof import('./src/components/home/MusicList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwpierTop: typeof import('./src/components/home/SwpierTop.vue')['default']
    TopNav: typeof import('./src/components/home/TopNav.vue')['default']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
